---
title: "Planejamento de Experimentos - I"
author: "Gabriel Lopes Rubinho"
date: '03-03-2024'
lang: pt
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: united
    highlight: tango

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Blocos Randomizados - Exercício 4.1

4.1. A ANOVA de um experimento de blocos completos casualizados tem o resultado abaixo


| Source | DF | SS | MS | F | P |
|---------|:-----|------:|:------:|:------:|:------:|
| Treatment      |   4 |   1010.56  |   ?   |   29.84   | ? |
| Block     | ?  |  ? |   64.765  |    ? |  ? |
| Error       |   20  |   169.33   |    ?   |       | |
| Total       |   29  |   1503.71   |       |       | |

a. Preencha os espaços em branco. Você pode dar limites no valor-p.  



Temos a seguinte equação: $SS{T} = SS_{Treatments} + SS_{Blocks} + SS_{E}$ (chamado de equação fundamental da ANOVA) onde $SS_{T}$ tem N-1 graus de liberdade(N é o número de observações), $SS_{Treatments}$ e $SS_{Blocks}$ têm a-1 e b-1 graus de liberdade (a é o número de tratamentos e b o número de blocos), e $SS_{E}$ (a-1)(b-1). Pela equação, $4 = a-1 \iff a = 5$; $20 = (5-1)(b-1) \iff b = 6$. Portanto, o número de graus de liberdade do `Block`, é $b-1 = 6-1 = 5$.  

Pela equação fundamental da ANOVA, $1503.71 = 169.33 + SS_{Block} + 1010.56 \iff SS_{Block} = 1503.71 - 169.33 - 1010.56 = 323.82$.  

$MS_{Treatment} = \frac{SS_{Treatment}}{a-1} = \frac{1010.56}{4} = 252.64$
$MS_{E} = \frac{SS_{E}}{(b-1)(a-1)} = \frac{169.33}{20}=8.4665$  

$F_{Block} = \frac{MS_{Block}}{MS_{E}} = \frac{64.765}{8.4665} = 7.64956$


$P_{Treatment} = 3.544848e-08$  

$P_{Block} = 0.0003688504$  

(Feitos utilizando o comando `pf` do R).

Portanto, a tabela ficará da seguinte forma:

| Source | DF | SS | MS | F | P |
|---------|:-----|------:|:------:|:------:|:------:|
| Treatment      |   4 |   1010.56  |   252.64   |   29.84   |3.544848e-08  |
| Block     | 5  |  323.82 |   64.765  |    7.64956 |  0.0003688504 |
| Error       |   20  |   169.33   |    8.4665   |       | |
| Total       |   29  |   1503.71   |       |       | |






\newline

(b) Quantos blocos foram usados nesse experimento?

Foram usados um total de b blocos. Como o número de graus de liberdade dos blocos é b-1, há um total de 6 blocos que foram utilizados.


(c) Que conclusões você pode ter?

É possível ter a conclusão de que há diferença significativa, tanto nos tratamentos, quanto nos blocos, pois o valor-p dos dois foi menor que 5\%. 


